#!/usr/bin/env bash
# Nginx on new Ubuntu machine

sudo apt-get update

sudo apt-get install -y nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

if sudo ss -tnl | grep -q ':80'; then
    echo "Nginx is listening on port 80."
else
    echo "Error: Nginx is not listening on port 80."
fi

NGINX_RESPONSE=$(curl -s http://127.0.0.1)

if [ "$NGINX_RESPONSE" == 'Hello World!' ]; then
    echo "Nginx is serving the Hello World! page."
else
    echo "Error: Nginx is not serving the Hello World! page."
fi
